backend:
  name: github
  repo: PEDROSO02/infotrend
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true

    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
